const holidays = {
  provinces: [
    {
      id: 'AB',
      nameEn: 'Alberta',
      nameFr: 'Alberta',
      sourceLink:
        'https://www.alberta.ca/alberta-general-holidays.aspx#jumplinks-1',
      sourceEn: 'General holidays in Alberta',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 4,
          date: '2023-02-20',
          nameEn: 'Family Day',
          nameFr: 'Fête de la famille',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'BC',
      nameEn: 'British Columbia',
      nameFr: 'Colombie-Britannique',
      sourceLink:
        'https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/statutory-holidays#body',
      sourceEn: 'Statutory Holidays in British Columbia',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 4,
          date: '2023-02-20',
          nameEn: 'Family Day',
          nameFr: 'Fête de la famille',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 19,
          date: '2023-08-07',
          nameEn: 'British Columbia Day',
          nameFr: 'Jour de Colombie-Britannique',
          federal: 0,
          observedDate: '2023-08-07',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 28,
          date: '2023-09-30',
          nameEn: 'National Day for Truth and Reconciliation',
          nameFr: 'Journée nationale de la vérité et de la réconciliation',
          federal: 1,
          observedDate: '2023-10-02',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'MB',
      nameEn: 'Manitoba',
      nameFr: 'Manitoba',
      sourceLink:
        'https://www.gov.mb.ca/labour/standards/doc,gen-holidays-after-april-30-07,factsheet.html#q12',
      sourceEn: 'General holidays in Manitoba',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 2,
          date: '2023-02-20',
          nameEn: 'Louis Riel Day',
          nameFr: 'Journée Louis Riel',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'NB',
      nameEn: 'New Brunswick',
      nameFr: 'Nouveau-Brunswick',
      sourceLink:
        'https://www2.gnb.ca/content/gnb/en/departments/elg/local_government/content/governance/content/days_of_rest_act/faq.html#2',
      sourceEn: '10 prescribed days of rest',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 4,
          date: '2023-02-20',
          nameEn: 'Family Day',
          nameFr: 'Fête de la famille',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 20,
          date: '2023-08-07',
          nameEn: 'New Brunswick Day',
          nameFr: 'Jour de Nouveau Brunswick',
          federal: 0,
          observedDate: '2023-08-07',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'NL',
      nameEn: 'Newfoundland and Labrador',
      nameFr: 'Terre-Neuve-et-Labrador',
      sourceLink:
        'https://gist.github.com/pcraig3/81dff348ddf52777c9f918c3032531bd',
      sourceEn: 'Public holidays in Newfoundland',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 6,
          date: '2023-03-17',
          nameEn: "Saint Patrick's Day",
          nameFr: 'Jour de la Saint-Patrick',
          federal: 0,
          observedDate: '2023-03-13',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 9,
          date: '2023-04-23',
          nameEn: "Saint George's Day",
          nameFr: 'Jour de St. George',
          federal: 0,
          observedDate: '2023-04-24',
        },
        {
          id: 14,
          date: '2023-06-24',
          nameEn: 'Discovery Day',
          nameFr: 'Journée découverte',
          federal: 0,
          observedDate: '2023-06-26',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 17,
          date: '2023-07-12',
          nameEn: "Orangemen's Day",
          nameFr: 'Fête des orangistes',
          federal: 0,
          observedDate: '2023-07-10',
        },
        {
          id: 24,
          date: '2023-08-02',
          nameEn: 'Regatta Day',
          nameFr: 'Journée des régates',
          federal: 0,
          observedDate: '2023-08-02',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
        {
          id: 32,
          date: '2023-12-26',
          nameEn: 'Boxing Day',
          nameFr: 'Lendemain de Noël',
          federal: 1,
          observedDate: '2023-12-26',
        },
      ],
      nextHoliday: {
        id: 14,
        date: '2023-06-24',
        nameEn: 'Discovery Day',
        nameFr: 'Journée découverte',
        federal: 0,
        observedDate: '2023-06-26',
      },
    },
    {
      id: 'NS',
      nameEn: 'Nova Scotia',
      nameFr: 'Nouvelle-Écosse',
      sourceLink: 'https://novascotia.ca/lae/employmentrights/holidaychart.asp',
      sourceEn: 'Paid holidays in Nova Scotia',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 5,
          date: '2023-02-20',
          nameEn: 'Heritage Day',
          nameFr: 'Fête du Patrimoine',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'NT',
      nameEn: 'Northwest Territories',
      nameFr: 'Territoires du Nord-Ouest',
      sourceLink:
        'https://www.ece.gov.nt.ca/en/services/employment-standards/frequently-asked-questions#Statutory%20Holidays',
      sourceEn: 'Employment Standards, Northwest Territories',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 12,
          date: '2023-06-21',
          nameEn: 'National Indigenous Peoples Day',
          nameFr: 'Journée nationale des peuples autochtones',
          federal: 0,
          observedDate: '2023-06-21',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 18,
          date: '2023-08-07',
          nameEn: 'Civic Holiday',
          nameFr: 'Congé civique',
          federal: 1,
          observedDate: '2023-08-07',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 28,
          date: '2023-09-30',
          nameEn: 'National Day for Truth and Reconciliation',
          nameFr: 'Journée nationale de la vérité et de la réconciliation',
          federal: 1,
          observedDate: '2023-10-02',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 12,
        date: '2023-06-21',
        nameEn: 'National Indigenous Peoples Day',
        nameFr: 'Journée nationale des peuples autochtones',
        federal: 0,
        observedDate: '2023-06-21',
      },
    },
    {
      id: 'NU',
      nameEn: 'Nunavut',
      nameFr: 'Nunavut',
      sourceLink: 'https://nu-lsco.ca/faq-s?tmpl=component&faqid=11',
      sourceEn: 'Nunavut General Holidays',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 16,
          date: '2023-07-09',
          nameEn: 'Nunavut Day',
          nameFr: 'Jour de Nunavut',
          federal: 0,
          observedDate: '2023-07-10',
        },
        {
          id: 18,
          date: '2023-08-07',
          nameEn: 'Civic Holiday',
          nameFr: 'Congé civique',
          federal: 1,
          observedDate: '2023-08-07',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 28,
          date: '2023-09-30',
          nameEn: 'National Day for Truth and Reconciliation',
          nameFr: 'Journée nationale de la vérité et de la réconciliation',
          federal: 1,
          observedDate: '2023-10-02',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'ON',
      nameEn: 'Ontario',
      nameFr: 'Ontario',
      sourceLink:
        'https://www.ontario.ca/document/your-guide-employment-standards-act-0/public-holidays',
      sourceEn: 'Ontario Public holidays',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 4,
          date: '2023-02-20',
          nameEn: 'Family Day',
          nameFr: 'Fête de la famille',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
        {
          id: 32,
          date: '2023-12-26',
          nameEn: 'Boxing Day',
          nameFr: 'Lendemain de Noël',
          federal: 1,
          observedDate: '2023-12-26',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'PE',
      nameEn: 'Prince Edward Island',
      nameFr: 'Île-du-Prince-Édouard',
      sourceLink:
        'https://www.princeedwardisland.ca/en/information/economic-growth-tourism-and-culture/paid-holidays',
      sourceEn: 'PEI Paid Holidays',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 3,
          date: '2023-02-20',
          nameEn: 'Islander Day',
          nameFr: 'Fête des Insulaires',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 28,
          date: '2023-09-30',
          nameEn: 'National Day for Truth and Reconciliation',
          nameFr: 'Journée nationale de la vérité et de la réconciliation',
          federal: 1,
          observedDate: '2023-10-02',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'QC',
      nameEn: 'Quebec',
      nameFr: 'Québec',
      sourceLink:
        'https://www2.gouv.qc.ca/entreprises/portail/quebec/ressourcesh?lang=fr&g=ressourcesh&sg=personnel&t=o&e=2318829344:3908165687',
      sourceEn: 'Jours fériés, chômés et payés',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 10,
          date: '2023-05-22',
          nameEn: "National Patriots' Day",
          nameFr: 'Journée nationale des patriotes',
          federal: 0,
          observedDate: '2023-05-22',
        },
        {
          id: 13,
          date: '2023-06-24',
          nameEn: 'Saint-Jean-Baptiste Day',
          nameFr: 'Saint-Jean-Baptiste / Fête nationale du Québec',
          federal: 0,
          observedDate: '2023-06-26',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 13,
        date: '2023-06-24',
        nameEn: 'Saint-Jean-Baptiste Day',
        nameFr: 'Saint-Jean-Baptiste / Fête nationale du Québec',
        federal: 0,
        observedDate: '2023-06-26',
      },
    },
    {
      id: 'SK',
      nameEn: 'Saskatchewan',
      nameFr: 'Saskatchewan',
      sourceLink:
        'https://www.saskatchewan.ca/business/employment-standards/public-statutory-holidays/list-of-saskatchewan-public-holidays',
      sourceEn: 'Saskatchewan Public Holidays',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 4,
          date: '2023-02-20',
          nameEn: 'Family Day',
          nameFr: 'Fête de la famille',
          federal: 0,
          observedDate: '2023-02-20',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 21,
          date: '2023-08-07',
          nameEn: 'Saskatchewan Day',
          nameFr: 'Jour de Saskatchewan',
          federal: 0,
          observedDate: '2023-08-07',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 15,
        date: '2023-07-01',
        nameEn: 'Canada Day',
        nameFr: 'Fête du Canada',
        federal: 1,
        observedDate: '2023-07-03',
      },
    },
    {
      id: 'YT',
      nameEn: 'Yukon',
      nameFr: 'Yukon',
      sourceLink:
        'https://yukon.ca/en/doing-business/employer-responsibilities/find-yukon-statutory-holiday',
      sourceEn: 'Yukon statutory holiday dates',
      holidays: [
        {
          id: 1,
          date: '2023-01-01',
          nameEn: "New Year's Day",
          nameFr: "Jour de l'An",
          federal: 1,
          observedDate: '2023-01-02',
        },
        {
          id: 7,
          date: '2023-04-07',
          nameEn: 'Good Friday',
          nameFr: 'Vendredi saint',
          federal: 1,
          observedDate: '2023-04-07',
        },
        {
          id: 11,
          date: '2023-05-22',
          nameEn: 'Victoria Day',
          nameFr: 'Fête de la Reine',
          federal: 1,
          observedDate: '2023-05-22',
        },
        {
          id: 12,
          date: '2023-06-21',
          nameEn: 'National Indigenous Peoples Day',
          nameFr: 'Journée nationale des peuples autochtones',
          federal: 0,
          observedDate: '2023-06-21',
        },
        {
          id: 15,
          date: '2023-07-01',
          nameEn: 'Canada Day',
          nameFr: 'Fête du Canada',
          federal: 1,
          observedDate: '2023-07-03',
        },
        {
          id: 25,
          date: '2023-08-21',
          nameEn: 'Discovery Day',
          nameFr: 'Jour de la Découverte',
          federal: 0,
          observedDate: '2023-08-21',
        },
        {
          id: 26,
          date: '2023-09-04',
          nameEn: 'Labour Day',
          nameFr: 'Fête du travail',
          federal: 1,
          observedDate: '2023-09-04',
        },
        {
          id: 28,
          date: '2023-09-30',
          nameEn: 'National Day for Truth and Reconciliation',
          nameFr: 'Journée nationale de la vérité et de la réconciliation',
          federal: 1,
          observedDate: '2023-10-02',
        },
        {
          id: 29,
          date: '2023-10-09',
          nameEn: 'Thanksgiving',
          nameFr: 'Action de grâce',
          federal: 1,
          observedDate: '2023-10-09',
        },
        {
          id: 30,
          date: '2023-11-11',
          nameEn: 'Remembrance Day',
          nameFr: 'Jour du Souvenir',
          federal: 1,
          observedDate: '2023-11-13',
        },
        {
          id: 31,
          date: '2023-12-25',
          nameEn: 'Christmas Day',
          nameFr: 'Noël',
          federal: 1,
          observedDate: '2023-12-25',
        },
      ],
      nextHoliday: {
        id: 12,
        date: '2023-06-21',
        nameEn: 'National Indigenous Peoples Day',
        nameFr: 'Journée nationale des peuples autochtones',
        federal: 0,
        observedDate: '2023-06-21',
      },
    },
  ],
};

export default holidays;
